tree: Events
eras:
  "2022C":
    luminosity: 4840 # pb^-1
dbcache: dascache
samples:
  MuonEG:
    era: "2022C"
    type: data
    group: "data"
    db: das:/MuonEG/Run2022C-PromptNanoAODv10-v1/NANOAOD
    run_range: [355794, 357486]
    certified_lumi_file: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json

  EGamma:
    era: "2022C"
    type: data
    group: "data"
    db: das:/EGamma/Run2022C-PromptNanoAODv10_v1-v1/NANOAOD
    run_range: [355794, 357486]
    certified_lumi_file: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json

  DoubleMuon:
    era: "2022C"
    type: data
    group: "data"
    db: das:/DoubleMuon/Run2022C-PromptNanoAODv10_v1-v1/NANOAOD
    run_range: [355794, 357486]
    certified_lumi_file: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json

  SingleMuon:
    era: "2022C"
    type: data
    group: "data"
    db: das:/SingleMuon/Run2022C-PromptNanoAODv10_v1-v1/NANOAOD
    run_range: [355794, 357486]
    certified_lumi_file: https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json

  TTbar:
    era: "2022C"
    group: "TTbar"
    type: mc
    cross-section: 880
    generated-events: genEventSumw
    files:
      - ../../data/TTbar/a870ad04-4e1e-42e9-9fa5-10402f3e01d1.root
  DY:
    era: "2022C"
    group: "DY"
    type: mc
    cross-section: 5711
    generated-events: genEventSumw
    files:
      - ../../data/DY/C4465203-C5DB-B848-A601-CB396449051A.root
      - ../../data/DY/B154D990-5925-7F43-8DE8-7BDC6449AD68.root
plotIt:
  configuration:
    width: 800
    height: 600
    margin-left: 0.2
    margin-right: 0.03
    margin-top: 0.05
    margin-bottom: 0.15
    luminosity-label: '%1$.2f fb^{-1} (8 TeV)'
    experiment: CMS
    extra-label: Run 3
    error-fill-style: 3154
    error-fill-color: "#ee556270"
    ratio-fit-error-fill-style: 1001
    ratio-fit-error-fill-color: "#aa556270"
    ratio-fit-line-color: "#0B486B"
    yields-table-align: v
  legend:
    position: [0.7, 0.6, 0.91, 0.91]
  groups:
    data:
      legend: data
      order: 2
    TTbar:
      legend: TTbar
      fill-color: "#99ccff"
      order: 3
    DY:
      legend: DY
      fill-color: "#9FFF33"
      order: 1
  plotdefaults:
    y-axis: Events
    log-y: both
    y-axis-show-zero: True
    save-extensions: [pdf]
    show-ratio: False
    sort-by-yields: False
